"""Shared data-quality vocabulary: severities, check codes, observations, reports.

Used by the Bronze checks (``ingestion.data_quality``) and the Silver checks
(``transformations.silver_quality``) so every layer reports in one format.
"""

from __future__ import annotations

from collections import Counter
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict


class Severity(StrEnum):
    ERROR = "ERROR"
    WARNING = "WARNING"
    INFO = "INFO"


SEVERITY_ORDER = {Severity.ERROR: 0, Severity.WARNING: 1, Severity.INFO: 2}


class CheckCode(StrEnum):
    # --- Bronze (Phase 2) ---
    REQUIRED_PROJECT_MISSING = "REQUIRED_PROJECT_MISSING"
    DUPLICATE_PROJECT_RECORD = "DUPLICATE_PROJECT_RECORD"
    PROJECT_MISSING_FROM_SOURCE = "PROJECT_MISSING_FROM_SOURCE"
    REGISTRY_METADATA_DIFFERENCE = "REGISTRY_METADATA_DIFFERENCE"
    MULTIPLE_LOANS_PER_PROJECT = "MULTIPLE_LOANS_PER_PROJECT"
    DUPLICATE_LOAN_IDENTIFIER = "DUPLICATE_LOAN_IDENTIFIER"
    UNRECOGNIZED_LOAN_NUMBER = "UNRECOGNIZED_LOAN_NUMBER"
    LOAN_SNAPSHOT_DATE = "LOAN_SNAPSHOT_DATE"
    SNAPSHOT_DATE_INCONSISTENT = "SNAPSHOT_DATE_INCONSISTENT"
    DUPLICATE_CONTRACT_IDENTIFIER = "DUPLICATE_CONTRACT_IDENTIFIER"
    PROCUREMENT_RECORDS_FOR_UNCOVERED_PROJECT = "PROCUREMENT_RECORDS_FOR_UNCOVERED_PROJECT"
    MISSING_REQUIRED_IDENTIFIER = "MISSING_REQUIRED_IDENTIFIER"
    MISSING_REQUIRED_VALUE = "MISSING_REQUIRED_VALUE"
    UNPARSEABLE_DATE = "UNPARSEABLE_DATE"
    UNPARSEABLE_AMOUNT = "UNPARSEABLE_AMOUNT"
    BLANK_SOURCE_COLUMN = "BLANK_SOURCE_COLUMN"
    BLANK_PROJECT_FIELDS = "BLANK_PROJECT_FIELDS"
    HTML_IN_TEXT_FIELD = "HTML_IN_TEXT_FIELD"
    SOURCE_CONCEPT_NOT_PROVIDED = "SOURCE_CONCEPT_NOT_PROVIDED"
    SOURCE_ROWS_WITHOUT_PROJECT_ID = "SOURCE_ROWS_WITHOUT_PROJECT_ID"
    PROJECT_COMMITMENT_SOURCE_DIFFERENCE = "PROJECT_COMMITMENT_SOURCE_DIFFERENCE"
    FINANCER_AMOUNT_FIELDS_DIFFER = "FINANCER_AMOUNT_FIELDS_DIFFER"
    DOCUMENT_DIRECTORY_MISSING = "DOCUMENT_DIRECTORY_MISSING"
    UNCLASSIFIED_DOCUMENT = "UNCLASSIFIED_DOCUMENT"
    CLASSIFICATION_CONFLICT = "CLASSIFICATION_CONFLICT"
    MANIFEST_FILE_CHANGED = "MANIFEST_FILE_CHANGED"
    MANIFEST_FILE_MISSING = "MANIFEST_FILE_MISSING"
    DUPLICATE_DOCUMENT_CONTENT = "DUPLICATE_DOCUMENT_CONTENT"
    FILENAME_PROJECT_MISMATCH = "FILENAME_PROJECT_MISMATCH"
    ISR_SEQUENCE_INCOMPLETE = "ISR_SEQUENCE_INCOMPLETE"
    ISR_SEQUENCE_DUPLICATE = "ISR_SEQUENCE_DUPLICATE"
    DOCUMENT_LOAN_REFERENCE_LINKED = "DOCUMENT_LOAN_REFERENCE_LINKED"
    DOCUMENT_LOAN_REFERENCE_UNLINKED = "DOCUMENT_LOAN_REFERENCE_UNLINKED"
    # --- Silver (Phase 3) ---
    SILVER_PROJECT_COUNT_MISMATCH = "SILVER_PROJECT_COUNT_MISMATCH"
    SILVER_EXPECTED_LOAN_MISSING = "SILVER_EXPECTED_LOAN_MISSING"
    SILVER_UNEXPECTED_LOAN = "SILVER_UNEXPECTED_LOAN"
    SILVER_DUPLICATE_LOAN = "SILVER_DUPLICATE_LOAN"
    LOAN_PROJECT_REFERENCE_BROKEN = "LOAN_PROJECT_REFERENCE_BROKEN"
    NEGATIVE_FINANCIAL_VALUE = "NEGATIVE_FINANCIAL_VALUE"
    LOAN_PRINCIPAL_COMPONENTS_DIFFERENCE = "LOAN_PRINCIPAL_COMPONENTS_DIFFERENCE"
    LOAN_DATE_ORDER_VIOLATION = "LOAN_DATE_ORDER_VIOLATION"
    LOAN_VALUATION_CAVEAT = "LOAN_VALUATION_CAVEAT"
    SOURCE_VALUE_NOT_NORMALIZABLE = "SOURCE_VALUE_NOT_NORMALIZABLE"
    SOURCE_STRUCTURE_ISSUE = "SOURCE_STRUCTURE_ISSUE"
    SOURCE_VALUE_CONFLICT = "SOURCE_VALUE_CONFLICT"
    PROCUREMENT_AWARD_AMOUNT_UNRESOLVED = "PROCUREMENT_AWARD_AMOUNT_UNRESOLVED"
    PROCUREMENT_COVERAGE_SEMANTICS_VIOLATION = "PROCUREMENT_COVERAGE_SEMANTICS_VIOLATION"
    PROCUREMENT_GRAIN_VIOLATION = "PROCUREMENT_GRAIN_VIOLATION"
    PROJECT_METADATA_INCOMPLETE = "PROJECT_METADATA_INCOMPLETE"
    FIELD_FROM_SECONDARY_SOURCE = "FIELD_FROM_SECONDARY_SOURCE"
    MISSING_PROVENANCE = "MISSING_PROVENANCE"
    FINANCIAL_SUMMARY_MISMATCH = "FINANCIAL_SUMMARY_MISMATCH"
    # --- Parsing (Phase 4) ---
    PARSE_FAILED = "PARSE_FAILED"
    PARSED_DOCUMENT_MISSING = "PARSED_DOCUMENT_MISSING"
    UNEXPECTED_DOCUMENT = "UNEXPECTED_DOCUMENT"
    SOURCE_HASH_CHANGED = "SOURCE_HASH_CHANGED"
    PDF_PAGE_COUNT_MISMATCH = "PDF_PAGE_COUNT_MISMATCH"
    EMPTY_PAGES = "EMPTY_PAGES"
    LOW_TEXT_EXTRACTION = "LOW_TEXT_EXTRACTION"
    LOW_TEXT_COVERAGE = "LOW_TEXT_COVERAGE"
    NO_USABLE_TEXT = "NO_USABLE_TEXT"
    DOCUMENT_PROJECT_MISMATCH = "DOCUMENT_PROJECT_MISMATCH"
    DOCUMENT_TYPE_UNRESOLVED = "DOCUMENT_TYPE_UNRESOLVED"
    METADATA_CORRECTED_FROM_DOCUMENT = "METADATA_CORRECTED_FROM_DOCUMENT"
    METADATA_CONFLICT = "METADATA_CONFLICT"
    MISSING_EXPECTED_METADATA = "MISSING_EXPECTED_METADATA"
    ISR_DATES_DIFFER = "ISR_DATES_DIFFER"
    TABLE_CELLS_DROPPED = "TABLE_CELLS_DROPPED"
    PAGE_PROVENANCE_INVALID = "PAGE_PROVENANCE_INVALID"
    PARSER_WARNING = "PARSER_WARNING"
    ISR_INVENTORY_INCOMPLETE = "ISR_INVENTORY_INCOMPLETE"
    # --- Document extraction (Phase 5) ---
    ISR_SNAPSHOT_MISSING = "ISR_SNAPSHOT_MISSING"
    ISR_DATE_DIFFERENCE = "ISR_DATE_DIFFERENCE"
    RATING_NOT_FOUND = "RATING_NOT_FOUND"
    UNKNOWN_RATING_VALUE = "UNKNOWN_RATING_VALUE"
    PDF_TEXT_FALLBACK_USED = "PDF_TEXT_FALLBACK_USED"
    EXTRACTION_CONFLICT = "EXTRACTION_CONFLICT"
    EXTRACTION_AMBIGUOUS = "EXTRACTION_AMBIGUOUS"
    RESULTS_TABLE_INVALID = "RESULTS_TABLE_INVALID"
    POSSIBLE_INDICATOR_MATCH = "POSSIBLE_INDICATOR_MATCH"
    RESTRUCTURING_DATE_UNRESOLVED = "RESTRUCTURING_DATE_UNRESOLVED"
    ORIGINAL_CLOSING_DATE_ESTABLISHED = "ORIGINAL_CLOSING_DATE_ESTABLISHED"
    ORIGINAL_CLOSING_DATE_UNRESOLVED = "ORIGINAL_CLOSING_DATE_UNRESOLVED"
    CROSS_SOURCE_DIFFERENCE = "CROSS_SOURCE_DIFFERENCE"
    CROSS_SOURCE_NOT_COMPARABLE = "CROSS_SOURCE_NOT_COMPARABLE"
    CROSS_SOURCE_AGREEMENT = "CROSS_SOURCE_AGREEMENT"
    OCR_NOT_REQUIRED_FOR_CURRENT_SCOPE = "OCR_NOT_REQUIRED_FOR_CURRENT_SCOPE"
    EXTRACTION_LIMITATION = "EXTRACTION_LIMITATION"
    # ISR canonical dates out of ISR sequence order (sequence stays the ordering key).
    SEQUENCE_DATE_ANOMALY = "SEQUENCE_DATE_ANOMALY"
    # --- Lakehouse / Delta platformization (Phase 6) ---
    SOURCE_HASH_MISMATCH = "SOURCE_HASH_MISMATCH"
    RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"


class Observation(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    check: CheckCode
    severity: Severity
    project_id: str | None = None
    source: str
    message: str
    explanation: str | None = None
    details: dict[str, Any] = {}


class DataQualityReport(BaseModel):
    model_config = ConfigDict(extra="forbid")

    generated_at: str
    ingestion_run_id: str
    observations: list[Observation]
    layer: str = "bronze"

    def counts(self) -> dict[str, int]:
        counter = Counter(o.severity.value for o in self.observations)
        return {s.value: counter.get(s.value, 0) for s in Severity}

    @property
    def has_errors(self) -> bool:
        return any(o.severity is Severity.ERROR for o in self.observations)

    def by_check(self, check: CheckCode) -> list[Observation]:
        return [o for o in self.observations if o.check is check]


def sort_observations(observations: list[Observation]) -> list[Observation]:
    """Errors first, then warnings, then info; stable within project and check."""
    return sorted(
        observations, key=lambda o: (SEVERITY_ORDER[o.severity], o.project_id or "", o.check)
    )
