"""Phase 9C: run the current 9B router over the DRAFT routing dataset (baseline only) and
write the human-review artefact.

Development rehearsal: Gold is built in memory with local Spark from the Phase 6 Silver
export (as in tests/spark/test_gold_real.py), so event anchors resolve against real
timeline dates. Nothing is persisted to Delta; no labels are changed; DOCUMENT routes are
recorded but not executed (no retrieval runs in the baseline).

    .venv-spark\\Scripts\\python scripts/routing_review_9c.py

Outputs: evaluation/routing_baseline_<router version>.yaml (generated) and
evaluation/routing_review_9c.md.
"""

from __future__ import annotations

import sys
from datetime import UTC, datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from worldbank_copilot.common import load_project_registry, load_settings  # noqa: E402
from worldbank_copilot.ingestion.documents import load_document_manifest  # noqa: E402
from worldbank_copilot.intelligence.frames import GoldContext  # noqa: E402
from worldbank_copilot.intelligence.pipeline import (  # noqa: E402
    build_gold,
    silver_from_json,
    validate_build,
)
from worldbank_copilot.intelligence.rules import load_rules, load_scales  # noqa: E402
from worldbank_copilot.lakehouse.spark_store import spark_schema  # noqa: E402
from worldbank_copilot.routing.config import load_routing_config  # noqa: E402
from worldbank_copilot.routing.entities import EntityIndex  # noqa: E402
from worldbank_copilot.routing.evaluation import load_dataset, metrics, run_baseline  # noqa: E402
from worldbank_copilot.routing.review import alias_rows, render  # noqa: E402
from worldbank_copilot.routing.service import RoutingService  # noqa: E402
from worldbank_copilot.tools.base import ToolContext  # noqa: E402
from worldbank_copilot.tools.reader import TABLES, InMemoryReader  # noqa: E402
from worldbank_copilot.tools.registry import default_executor  # noqa: E402


def governed_rows(settings) -> dict[str, list[dict]]:
    from pyspark.sql import SparkSession

    spark = (
        SparkSession.builder.master("local[2]")
        .config("spark.ui.enabled", "false")
        .config("spark.sql.session.timeZone", "UTC")
        .config("spark.sql.shuffle.partitions", "2")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("ERROR")
    export = settings.local_output_root / "lakehouse"
    silver = silver_from_json(spark, export)
    rules, scales = load_rules(settings.config_dir), load_scales(settings.config_dir)
    build = build_gold(
        spark,
        silver,
        rules,
        scales,
        GoldContext("review", "9c", datetime(2026, 10, 1, tzinfo=UTC), "9c"),
    )
    validate_build(build)
    rows = {}
    for logical, contract_fn in TABLES.items():
        layer, name = logical.split(".", 1)
        if layer == "gold":
            frame = build.frames[name]
        else:
            contract = contract_fn()
            frame = (
                spark.read.schema(spark_schema(contract))
                .option("mode", "FAILFAST")
                .json(str(export / f"{logical}.jsonl"))
                .select(*contract.column_names)
            )
        rows[logical] = [r.asDict(recursive=True) for r in frame.collect()]
    spark.stop()
    return rows


def main() -> None:
    settings = load_settings("local", env={})
    registry = load_project_registry(settings.config_dir)
    config = load_routing_config(settings.config_dir)
    manifest = load_document_manifest(settings.config_dir / "document_manifest.yaml")
    rules, scales = load_rules(settings.config_dir), load_scales(settings.config_dir)
    rows = governed_rows(settings)
    service = RoutingService(
        config,
        EntityIndex.build(registry, manifest, config),
        default_executor(),
        lambda rid: ToolContext(InMemoryReader(rows), registry, scales, rules, request_id=rid),
        documents=None,
    )
    dataset = load_dataset(ROOT / "evaluation" / "routing_cases.yaml")
    baseline = run_baseline(service, dataset, tuple(registry.project_ids))
    version = config.settings.router_version
    header = (
        "# GENERATED by scripts/routing_review_9c.py - do not edit.\n"
        f"# Deterministic router {version} output for each DRAFT case (baseline measurement\n"
        "# only; not ground truth). DOCUMENT routes were recorded, not executed.\n"
    )
    payload = {
        "router_versions": config.versions,
        "metrics": metrics(dataset, baseline),
        "results": [b.model_dump(mode="json") for b in baseline],
    }
    out = ROOT / "evaluation" / f"routing_baseline_{version}.yaml"
    out.write_text(
        header + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )
    original_path = ROOT / "evaluation" / "routing_baseline_9B.1.yaml"
    original = (
        yaml.safe_load(original_path.read_text(encoding="utf-8"))["metrics"]
        if original_path.exists() and version != "9B.1"
        else None
    )
    review = render(
        dataset,
        baseline,
        alias_rows(config.aliases, registry),
        config.aliases.reviewed_by,
        original=original,
        router_version=version,
    )
    (ROOT / "evaluation" / "routing_review_9c.md").write_text(review, encoding="utf-8")
    print(yaml.safe_dump(payload["metrics"], sort_keys=False))


if __name__ == "__main__":
    main()
